name: ERT

on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@v3.0
        with:
          version: 28.1

      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Clone verilog-ext
        uses: actions/checkout@v2
        with:
          path: verilog-ext

      - name: Install binaries
        run: |
          cd $GITHUB_WORKSPACE/verilog-ext
          .github/scripts/setup-env.sh

      - name: Run ERT tests
        run: |
          cd $GITHUB_WORKSPACE/verilog-ext
          .github/scripts/ert-tests.sh
